{
 "title": "OpsWatch",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avg attempts per check (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(opswatch_check_attempts_sum[5m]))\r\n/\r\nsum(rate(opswatch_check_attempts_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 check duration (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, type) (rate(opswatch_check_duration_seconds_bucket[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Percent (0-1)" } },
   "targets": [
    {
     "expr": "sum(rate(opswatch_checks_total{success=\"true\"}[5m]))\r\n/\r\nsum(rate(opswatch_checks_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(opswatch_checks_total[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}